// Planet content — richer, real details from Anvita.

const PLANETS = [
  {
    id: 'sun',
    name: 'Core',
    role: 'Who I Am',
    teaser: '',
    orbitR: 0,
    size: 110,
    speed: 0,
    tint: '#e8a87c',
    glow: '#f4c089',
    angle: 0,
    bodyType: 'sun',
    detail: {
      component: 'who',
      kicker: 'Core identity',
      title: 'Anvita Singh',
      subtitle: 'Engineer turning product manager. Building with care.',
      body: [
        'I spent three years shipping infrastructure that hundreds of engineers relied on every day.',
        'Somewhere along the way I realized I cared more about the why than the how — about decisions, users, taste, and the rooms where products get shaped.',
        'So I stepped off the path on purpose. Got curious. Studied PM craft. Sat with discomfort.',
        'Now I\u2019m looking for the next orbit: a PM or Chief of Staff role where I can be in the room when the product is being decided.',
      ],
      tags: ['ex-engineer', 'PM fellowship', 'founder fellowship', 'AI-curious', 'systems-thinker'],
    },
  },
  {
    id: 'journey',
    name: 'Archiva',
    role: 'My Journey',
    teaser: 'mission log: 2022 \u2192 now',
    orbitR: 220,
    orbitTilt: -22,
    orbitYScale: 0.36,
    size: 46,
    speed: 0.07,
    tint: '#9b6a6c',
    glow: '#b88a8c',
    angle: 250,
    bodyType: 'ringed',
    detail: { kicker: 'Professional journey', title: 'Flight path', component: 'journey' },
  },
  {
    id: 'projects',
    name: 'Atelier',
    role: 'Projects',
    teaser: 'a constellation of case studies',
    orbitR: 330,
    orbitTilt: -8,
    orbitYScale: 0.30,
    size: 38,
    speed: 0.10,
    tint: '#c98a6b',
    glow: '#e0a482',
    angle: 30,
    bodyType: 'rocky',
    detail: { kicker: 'Projects', title: 'Eight stars in a constellation', component: 'projects' },
  },
  {
    id: 'skills',
    name: 'Arsenal',
    role: 'Skills',
    teaser: 'the tools I carry',
    orbitR: 470,
    size: 30,
    speed: 0.13,
    tint: '#a88cc4',
    glow: '#c4a8e0',
    angle: 90,
    bodyType: 'rocky',
    detail: { kicker: 'Skills', title: 'Arsenal', component: 'skills' },
  },
  {
    id: 'about',
    name: 'Lune',
    role: 'About Me',
    teaser: 'who I am off the clock',
    orbitR: 640,
    orbitTilt: 18,
    orbitYScale: 0.22,
    size: 28,
    speed: 0.16,
    tint: '#d6a8a8',
    glow: '#e8c4c4',
    angle: 140,
    bodyType: 'moon',
    detail: { kicker: 'About', title: 'Galaxies', component: 'about' },
  },
  {
    id: 'contact',
    name: 'Outpost',
    role: 'Contact',
    teaser: 'send a transmission',
    orbitR: 860,
    orbitTilt: -4,
    orbitYScale: 0.32,
    size: 22,
    speed: 0.035,
    tint: '#7a3b4a',
    glow: '#a85d6c',
    angle: 200,
    bodyType: 'rocky',
    detail: { kicker: 'Contact', title: 'Open a channel', component: 'contact' },
  },
];

const PROJECTS = [
  {
    id: 'p1', kind: 'Presentation', year: '2025', mag: 1.1,
    x: -0.82, y: 0.52,
    title: 'Brilliant Replies, Buried Alive',
    tag: 'AI · product feature',
    blurb: 'A feature teardown of ChatGPT\'s conversation discovery problem.',
    lede: 'As conversations grow longer and denser, valuable replies get buried. I diagnosed the gap and designed a native bookmarking and tagging system for 900M weekly users.',
    role: 'Feature Analysis', duration: 'ProductSpace IA-1',
    deckUrl: 'pdfs/chatgpt-feature-analysis.pdf',
  },
  {
    id: 'p2', kind: 'Case study', year: '2025', mag: 1.2,
    x: -0.32, y: 0.78,
    thumbUrl: 'assets/projects/linkedin-logo.png',
    title: 'LinkedIn: Grow the Feed',
    tag: 'social · engagement',
    blurb: 'Improving mobile engagement and retention for a billion professionals.',
    lede: 'LinkedIn\'s moat is its professional graph — but the mobile feed isn\'t keeping career climbers coming back. I redesigned discovery and engagement for the platform\'s most active segment.',
    role: 'Product Improvement', duration: 'ProductSpace IA-5',
    caseUrl: 'pdfs/linkedin-product-improvement.pdf',
  },
  {
    id: 'p3', kind: 'Presentation', year: '2025', mag: 1.0,
    x: 0.62, y: 0.62,
    title: 'Blinkit Product Strategy',
    tag: 'quick commerce · strategy',
    blurb: 'A product strategy deck for Blinkit\'s next phase of growth.',
    lede: 'Mapping Blinkit\'s opportunity space beyond groceries — where quick commerce goes when speed is no longer the differentiator.',
    role: 'Strategy Deck', duration: 'ProductSpace',
    deckUrl: 'https://gamma.app/docs/PRODUCT-STRATEGY-DECK-aohyfttieod50as',
  },
  {
    id: 'p4', kind: 'Presentation', year: '2025', mag: 0.9,
    x: -0.08, y: 0.42,
    title: 'Groww: Reducing Choice Overload',
    tag: 'fintech · UX',
    blurb: 'Reducing decision fatigue in portfolio allocation for retail investors.',
    lede: 'Retail investors on Groww face overwhelming choice when allocating across asset classes. I mapped the friction and designed a guided allocation experience.',
    role: 'Product Improvement', duration: 'ProductSpace',
    deckUrl: 'https://gamma.app/docs/Groww-u336t8zvof2vukt',
  },
  {
    id: 'p5', kind: 'Case study', year: '2025', mag: 1.0,
    x: -0.62, y: -0.18,
    thumbUrl: 'assets/projects/netflix-logo.png',
    title: 'Netflix AVD Drop',
    tag: 'streaming · analytics',
    blurb: 'A root cause analysis of a 10% week-over-week drop in viewing time.',
    lede: 'Diagnosing a uniform 10% drop in Average View Duration across all segments, platforms, and geographies — working backward from data to root cause.',
    role: 'Root Cause Analysis', duration: 'ProductSpace IA-6',
    caseUrl: 'pdfs/netflix-rca.pdf',
  },
  {
    id: 'p6', kind: 'Case study', year: '2025', mag: 1.3,
    x: -0.05, y: -0.08,
    thumbUrl: 'assets/projects/cookease-logo.png',
    title: 'CookEase',
    tag: 'marketplace · India',
    blurb: 'A 0→1 product design for on-demand home cooks in Indian cities.',
    lede: 'Working professionals in Tier-1 India want healthy, transparent, home-cooked meals — but the market is entirely unorganized. I designed the product from scratch.',
    role: 'Product Design', duration: 'ProductSpace IA-7',
    caseUrl: 'pdfs/home-cook-product-design.pdf',
  },
  {
    id: 'p9', kind: 'PRD', year: '2025', mag: 1.05,
    x: 0.26, y: -0.72,
    thumbUrl: 'assets/projects/uber-logo.png',
    title: 'Ride-Sharing App: Safety Assurance Mode',
    tag: 'mobility · rider safety',
    blurb: 'A proactive ride-safety PRD for high-risk trips and low-effort protection.',
    lede: 'Uber\'s safety stack exists, but it still puts too much activation burden on the rider in the moments that matter most. I designed a proactive safety assurance mode for solo female riders and late-night travellers.',
    role: 'PRD', duration: 'Notion PRD',
    caseUrl: 'https://www.notion.so/Ride-Sharing-App-Safety-Assurance-Mode-32898672403b8064b5eccfe4bf18b5ca?source=copy_link',
  },
  {
    id: 'p10', kind: 'PRD', year: '2025', mag: 1.0,
    x: 0.86, y: 0.08,
    thumbUrl: 'assets/projects/zomato-logo.png',
    title: 'Zomato: Local Farm-to-Table Discovery',
    tag: 'food delivery · sourcing',
    blurb: 'A PRD for making local sourcing visible across food discovery and choice.',
    lede: 'Zomato helps users filter for calories, protein, and price — but not for where ingredients come from. I designed a discovery layer that helps users find locally sourced meals while giving restaurants and small farmers a stronger signal in the chain.',
    role: 'PRD', duration: 'Notion PRD',
    caseUrl: 'https://www.notion.so/Food-Delivery-App-Local-Farm-to-Table-Discovery-Zomato-32898672403b803f84d8c2b1df69bcfa?source=copy_link',
  },
  {
    id: 'p7', kind: 'Vibe-coded', year: '2025', mag: 1.1, video: true,
    x: 0.52, y: -0.32,
    title: 'Wandr',
    tag: 'AI · travel',
    blurb: 'Your AI travel companion that plans, adapts, and remembers.',
    lede: 'Built for the traveller who hates itinerary apps but still needs one. Wandr learns your style and builds trips around it.',
    role: 'Solo build', duration: '2025',
    appUrl: 'https://wandr-sooty.vercel.app/',
    deckUrl: 'https://gamma.app/docs/THANK-YOU-wtodgqo32vfrg0y',
  },
  {
    id: 'p8', kind: 'Vibe-coded', year: '2025', mag: 1.0, video: true,
    x: 0.82, y: -0.58,
    title: 'Wedly',
    tag: 'AI · consumer',
    blurb: 'Your AI wedding planner that takes the chaos out of the big day.',
    lede: 'Wedding planning involves hundreds of decisions, vendors, and timelines. Wedly coordinates all of it so the couple doesn\'t have to.',
    role: 'Solo build', duration: '2025',
    appUrl: 'https://wedly-lyart.vercel.app/login',
    deckUrl: 'https://gamma.app/docs/WEDLY-ad3ofuih4627tst',
  },
];

// Constellation edges (pairs of project ids)
const PROJECT_EDGES = [
  ['p1','p2'], // ChatGPT ↔ LinkedIn (both professional productivity)
  ['p1','p7'], // ChatGPT ↔ Wandr (both AI products)
  ['p2','p5'], // LinkedIn ↔ Netflix (both engagement metric problems)
  ['p2','p4'], // LinkedIn ↔ Groww (both consumer retention)
  ['p3','p4'], // Blinkit ↔ Groww (both Indian consumer)
  ['p3','p8'], // Blinkit ↔ Wedly (both convenience + planning)
  ['p3','p10'], // Blinkit ↔ Zomato (both Indian delivery / commerce)
  ['p5','p6'], // Netflix ↔ CookEase (both about consumption habits)
  ['p6','p10'], // CookEase ↔ Zomato (both food supply / meal choice)
  ['p6','p7'], // CookEase ↔ Wandr (both experiential consumer)
  ['p9','p10'], // Uber ↔ Zomato (both consumer PRDs)
  ['p2','p9'], // LinkedIn ↔ Uber (both retention / trust behaviour)
  ['p7','p8'], // Wandr ↔ Wedly (both AI life companions)
];

const JOURNEY = [
  {
    id: 's1',
    code: 'STATION 01',
    period: 'Feb \u2014 Jul 2022',
    place: 'GoTo · Bangalore',
    role: 'Associate Software Engineer · Intern',
    log: [
      'First contact with production code. Six months of small features, smaller bugs, big lessons.',
      'Learned what \u201cdone\u201d actually means \u2014 in tests, in reviews, in user-facing change.',
    ],
  },
  {
    id: 's2',
    code: 'STATION 02',
    period: 'Aug 2022 \u2014 Apr 2025',
    place: 'Palo Alto Networks · Bangalore',
    role: 'Software Engineer',
    log: [
      'Stopped thinking of myself as someone who writes code and started thinking of myself as someone who decides what gets built and why.',
      'Realized the dashboards I was building were not just tools. They were arguments for where to invest, what to deprecate, and who to trust with what.',
      'The hardest part was never the engineering. It was convincing six teams with six different priorities that one solution could serve all of them.',
      'Learned that adoption is not a feature you ship. It is a relationship you earn \u2014 80% adherence happened because we designed for trust, not compliance.',
      'Spent three years watching product decisions get made in rooms I was not in. Started walking into those rooms anyway.',
    ],
    metrics: [
      { v: '75%', l: 'org adoption' },
      { v: '80%', l: 'team adherence' },
      { v: '3 yrs', l: 'shipping' },
    ],
  },
  {
    id: 's3',
    code: 'STATION 03',
    period: 'May 2025 \u2014 present',
    place: 'Intentional break',
    role: 'Studying. Choosing. Recalibrating.',
    log: [
      'Left my job for family reasons. The exit was not a choice. Everything after it was.',
      'Explored DevOps because I genuinely liked it \u2014 cleared CKA, CKAD, Terraform, and AWS back to back.',
      'But kept drifting toward the product side. Signed up for a PM fellowship and a Founders Office fellowship to test the instinct.',
      'The instinct was right. I do not want to sit behind a laptop while AI writes the code. I want to be in the room where the product is being decided.',
      'This break did not set me back. It made me specific about what I want and why.',
    ],
    metrics: [
      { v: '4', l: 'certifications cleared' },
      { v: '2', l: 'fellowships joined' },
      { v: '1', l: 'clear answer found' },
    ],
  },
  {
    id: 's4',
    code: 'NEXT JUMP',
    period: 'incoming',
    place: 'Product Manager · Chief of Staff',
    role: 'Not looking for any role. Looking for the right one.',
    log: [
      'I want a PM or Chief of Staff role where I am not decorating someone else\'s roadmap — I am shaping it.',
      'I want to work with a team that treats taste, clarity, and conviction as real skills — not soft skills.',
      'I bring three years of engineering depth, four months of deliberate reinvention, and the kind of user empathy you only get when you have been the user who hated the tool.',
      'Bonus points if the product is AI-native, the team is small enough to be dangerous, and the pace is "ship it Thursday, learn by Monday."',
      'I am not trying to prove I can do this. I am trying to find the people who already see it.',
    ],
    metrics: [
      { v: '1', l: 'conviction' },
      { v: '0', l: 'interest in settling' },
    ],
  },
];

const SKILL_ORBS = [
  {
    id: 'tech',
    title: 'Technical',
    sub: 'What I build',
    icon: '⚙',
    orbLeft: '22%',
    orbTop: '25%',
    orbSize: 200,
    color: 'green',
    cert: 'Certified in (CKA · CKAD · Terraform · AWS)',
    skills: [
      { name: 'Python', left: '5%', top: '5%' },
      { name: 'SQL', left: '18%', top: '3%' },
      { name: 'AWS', left: '33%', top: '5%' },
      { name: 'Kubernetes', left: '3%', top: '18%' },
      { name: 'Docker', left: '38%', top: '16%' },
      { name: 'Terraform', left: '6%', top: '38%' },
      { name: 'CI/CD', left: '22%', top: '42%' },
      { name: 'Git', left: '3%', top: '48%' },
      { name: 'Grafana', left: '36%', top: '38%' },
      { name: 'Prometheus', left: '20%', top: '50%' },
    ],
  },
  {
    id: 'prod',
    title: 'Product',
    sub: 'How I think',
    icon: '◇',
    orbLeft: '76%',
    orbTop: '25%',
    orbSize: 210,
    color: 'rose',
    skills: [
      { name: 'Product strategy', left: '56%', top: '4%' },
      { name: 'Roadmapping', left: '74%', top: '3%' },
      { name: 'PRD writing', left: '88%', top: '6%' },
      { name: 'User research', left: '58%', top: '16%' },
      { name: 'Product design', left: '86%', top: '17%' },
      { name: 'Product improvement', left: '56%', top: '38%' },
      { name: 'RCA', left: '88%', top: '36%' },
      { name: 'Stakeholder alignment', left: '58%', top: '48%' },
      { name: 'A/B testing', left: '80%', top: '46%' },
      { name: 'KPI design', left: '72%', top: '50%' },
      { name: 'Cross-functional', left: '90%', top: '48%' },
    ],
  },
  {
    id: 'ai',
    title: 'AI &\nautomation',
    sub: 'The new layer',
    icon: '✦',
    orbLeft: '50%',
    orbTop: '68%',
    orbSize: 220,
    color: 'purple',
    skills: [
      { name: 'Claude Code', left: '12%', top: '58%' },
      { name: 'Cursor', left: '28%', top: '56%' },
      { name: 'Codex', left: '72%', top: '56%' },
      { name: 'Vibe coding', left: '86%', top: '58%' },
      { name: 'Agentic AI', left: '10%', top: '80%' },
      { name: 'RAG', left: '26%', top: '84%' },
      { name: 'N8N', left: '74%', top: '82%' },
      { name: 'Zapier', left: '88%', top: '80%' },
      { name: 'Prompt engineering', left: '20%', top: '92%' },
      { name: 'LLM APIs', left: '42%', top: '90%' },
      { name: 'GenAI lifecycle', left: '60%', top: '92%' },
      { name: 'Model evaluation', left: '80%', top: '90%' },
    ],
  },
];

window.PLANETS = PLANETS;
window.PROJECTS = PROJECTS;
window.PROJECT_EDGES = PROJECT_EDGES;
window.JOURNEY = JOURNEY;
window.SKILL_ORBS = SKILL_ORBS;
